name: Quote
type: object
description: A <blockquote>, using text and cite, with large quote icons
properties:
  block:
    description: Whether this is a block component or not
    default: false
  text:
    type: string
    default: The creation of a thousand forests is in one acorn.
  cite:
    type: string
    default: Ralph Waldo Emerson
  iconOpen:
    type: string
    description: Iconify icon identifier for opening quote
  iconClose:
    type: string
    description: Iconify icon identifier for closing quote
