name: Quote
description: A <blockquote>, using text and cite, with large quote icons
props:
  text:
    type: string
    default: The creation of a thousand forests is in one acorn.
  cite:
    type: string
    default: Ralph Waldo Emerson
