title: Quote
type: object
description: A <blockquote>, using text and cite, with large quote icons
additionalProperties: false
required: ["component","block"]
properties:
  component:
    type: string
    default: Quote
    description: This specifies which component and schema is being used. It's mostly for internal purposes.
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  text:
    type: string
    default: ""
  cite:
    type: string
    default: ""
  iconOpen:
    type: string
    description: Iconify icon identifier for opening quote
  iconClose:
    type: string
    description: Iconify icon identifier for closing quote

examples: [{cite: "Ralph Waldo Emerson", text: "The creation of a thousand forests is in one acorn."}]
