name: Figure
type: object
description: ""
properties:
  block:
    description: Whether this is a block component or not
    default: false
  id:
    type: string
    default: null
  code:
    type: string
    default: null
  imgSrc:
    type: string
    default: null
  icon:
    type: string
    default: null
  figcaption:
    type: string
    text: ""
