name: Figure
description: ""
block: false
props:
  id:
    type: string
    default: null
  code:
    type: string
    default: null
  imgSrc:
    type: string
    default: null
  icon:
    type: string
    default: null
  figcaption:
    type: string
    text: ""
