title: Button
type: object
description: ""
required: ["text"]
properties:
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  text:
    type: string
    default: null
  action:
    type: string
    default: null
  class:
    type: string
    default: null
