name: CardGrid
type: object
description: ""
properties:
  block:
    description: Whether this is a block component or not
    default: true
  headline:
    type: string
    default: ""
  cards:
    type: array
    default: '[]'
    items:
      type: object
      props: 
        headline:
          type: string
        text:
          type: string
        icon:
          type: string

