title: SEO
type: object
description: "A head management component that dynamically injects SEO meta tags, Open Graph, and Twitter card data based on the provided `meta` properties."
properties:
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  title:
    type: string
    description: The page or site title.
    default: ""

  author:
    type: string
    description: The author name for meta tags.
    default: ""

  keywords:
    type: string
    description: Meta keywords
    default: ""

  description:
    type: string
    description: Short description for SEO and social previews.
    default: >
      A backpackerâ€™s journal of slow travel, mountain trails, and offbeat adventures around the world.
      Tips, stories, and inspiration for life on the move.

  image:
    type: string
    format: uri
    description: URL of the preview image used in Open Graph and Twitter cards.
    default:  ""

  iso_language:
    type: string
    default: "en"
  iso_country:
    type: string
    default: "US"

  card:
    type: string
    enum: [summary, summary_large_image, app, player]
    description: The Twitter card type.
    default: "summary_large_image"

  url:
    type: string
    format: uri
    description: The canonical URL of the page.
    default: ""

  type:
    type: string
    description: Open Graph type (e.g., website, article, profile).
    default: "website"

  social:
    type: object
    default: {}
    properties:
      twitter:
        type: string
        description: Twitter handle (with @) for attribution.
        default: ""

  robots:
    type: string
    description: Robots meta tag content.
    default: "index, follow"

  fbAppId:
    type: string
    description: Facebook App ID for Open Graph integration.
    default: ""

  latitude:
    type: string
    description: Optional latitude for geotagging.
    default: ""

  longitude:
    type: string
    description: Optional longitude for geotagging.
    default: ""

  icon:
    type: object
    description: Icon and favicon configuration.
    default: {}
    properties:
      main:
        type: string
        default: "/favicon.svg"
      legacy:
        type: string
        default: "/favicon.ico"
      small:
        type: string
        default: "/favicon.svg"
      large:
        type: string
        default: "/favicon.svg"
