name: CardGrid
description: ""
props:
  cards:
    type: array
    default: '[]'
    items:
      type: object
      props: 
        headline:
          type: string
        text:
          type: string
        icon:
          type: string

