name: Hero
block: true
description: >
  Hero component with headline, subheadline, call-to-actions, image, and styling options.

props:
  headline:
    type: string
    default: "<What do you do?>"
    description: "Primary headline text"
  subheadline:
    type: string
    default: "<Why Does that matter?>"
    description: "Secondary headline text"

  ctaPrimaryText:
    type: string
    default: "<Get Now>"
    description: "Primary call to action text"
  ctaPrimaryAction:
    type: string
    default: "tel:123"
    description: "Primary call to action"

  ctaSecondaryText:
    type: string
    default: "<Convince me first>"
    description: "Secondary call to action text"
  ctaSecondaryAction:
    type: string
    default: "#about"
    description: "Secondary call to action"

  googleReviewLink:
    type: string
    default: ""
    description: "Link to Google review"

  imgSrc:
    type: string
    name: "Image src"
    default: "https://images.pexels.com/photos/547115/pexels-photo-547115.jpeg"
    description: "Image source URL"
  imgAlt:
    type: string
    name: "Image Alt"
    default: ""
    description: "Image alt text for screenreaders."

  icon:
    type: string
    default: ""
    description: "Iconify icon identifier"

  style:
    type: string
    default: ""
    description: "Additional styles"

  imgOpacity:
    type: string
    name: Image Opacity
    default: ".4"
    description: "Opacity for the image"

  backgroundColor:
    type: string
    default: "black"
    description: "Background color"

  height:
    type: string
    default: "70vh"
    description: "Height of the component"

