name: Column
type: object
description: ""
properties:
  block:
    description: Whether this is a block component or not
    default: true
  background:
    type: string
    default: ""
  text:
    type: string
    default: ""
  heading:
    type: string
    default: ""
#  children:
#    description: Child components for the slot
