name: Column
description: ""
block: true
props:
  background:
    type: string
    default: ""
  text:
    type: string
    default: ""
  heading:
    type: string
    default: ""
  children:
    description: Child components for the slot
