title: Card
type: object
description: ""
properties:
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  id:
    type: string
    default: null
  headline:
    type: string
    default: null
  text:
    type: string
    default: null
  imgSrc:
    type: string
    default: null
  imgAlt:
    type: string
    default: null
  icon:
    type: string
    default: null
  chart:
    type: string
    default: null
  code:
    type: string
    default: null
