title: Navbar
type: object
description: A Navigation Bar for a website
additionalProperties: false
required: ["component","block"]
properties:
  component:
    type: string
    default: Navbar
    description: This specifies which component and schema is being used. It's mostly for internal purposes.
  block:
    type: boolean
    description: Whether this is a block component or not
    default: true
  links:
    type: array
    default: []
