name: FullPageTitle
type: object
description: ""
additionalProperties: false
properties:
  id:
    type: string
    description: Specify an id attribute for the component
    default: null
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  background:
    type: string
    default: ""
  color:
    type: string
    default: ""
  font:
    type: string
    default: ""
  headline:
    type: string
    description: A header for this component
  subheadline:
    type: string
    description: A subheadline for this component
