title: Theme
type: object
description: ""
additionalProperties: false
required: ["component","block"]
properties:
  component:
    type: string
    default: Theme
    description: This specifies which component and schema is being used. It's mostly for internal purposes.
    required: true
  id:
    type: string
    description: Specify an id attribute for the component
    default: ""
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false

  font:
    type: object
    description: The Fonts for the site's theme
    properties:
      heading:
        type: string
      body:
        type: string
  color:
    type: object
    description: Core color system for the site's theme.
    default: {}
    properties:
      base:
        type: string
        description: "The Base color is used as the primary background of the page"
        default: "rgba(250,250,250,.99)"
      surface:
        type: string
        description: "The Surface color is used for background colors of large sections which are above the base"
        default: ""
      brand:
        type: string
        description: "The Accent color is used for brand items, secondary buttons, and UI"
        default: ""
      accent:
        type: string
        description: "This is used for more important, primary buttons, like a cta"
        default: ""
      support:
        type: string
        description: "Additional Highlights and blends"
        default: ""
#      theme:
#        type: string
#        default: "oklch(99% 1% 230deg)"
#      themeLight:
#        type: string
#        default: "oklch(99% 1% 230deg)"
#      themeDark:
#        type: string
#        default: "oklch(1% 2% 30deg)"

  revenge:
    type: boolean
    description: Include What Revenge css warnings.
    default: false

