title: Map
type: object
description: A Svelte Map component made with Leaflet
properties:
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  latitude:
    type: number
    default: 40.730610
  longitude:
    type: number
    default: -73.935242
  zoom:
    type: integer
    default: 12
  height: 
    type: number
    default: "20rem"
  width:
    type: string
    default: "100%"
  sensitivity: 
    type: integer
    default: 500
