name: Accordion
type: object
description: ""
properties:
  id:
    type: string
    default: ""
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  summary:
    type: string
    default: ""
  details:
    type: string
    default: ""
