title: Accordion
type: object
description: ""
additionalProperties: false
required: ["component","block"]
properties:
  component:
    type: string
    default: Accordion
    description: This specifies which component and schema is being used. It's mostly for internal purposes.
  block:
    type: boolean
    description: Whether this is a block component or not
    default: false
  id:
    type: string
    default: ""
  summary:
    type: string
    default: ""
  details:
    type: string
    default: ""
